### ISSUE TITLE
Bug in EditForm - Unhandled Promise 

### ISSUE THREAD

**Issue by olympiawoj** [Lambda-School-Labs/cooking-recipe-source-control-fe#33]
**Error**: Unhandled Promise Rejection
**Reason**: There are no steps so mapping through the steps are throwing an error 

**Link to Code Line:** 
https://github.com/Lambda-School-Labs/cooking-recipe-source-control-fe/blob/5de1b419dd5434877557a8c0117ab99c60d634c9/components/EditForm.js#L93

**Comment by olympiawoj** [comment]
Need to add error handling when adding a recipe - if there are no steps, then they shouldn't be able to add a recipe.

**Comment by jambis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug Tracker](https://trello.com/c/ccb16Hij/22-bug-tracker)

**Comment by DevWarr** [comment]
Issue fixed in most recent merge to master. Closing Issue.
