### ISSUE TITLE
Remove console.logs()

### ISSUE THREAD

**Issue by olympiawoj** [Lambda-School-Labs/cooking-recipe-source-control-fe#35]
**Issue**: Too many console.logs() in terminal
**Solution**: Remove all console.logs()

**Comment by windixxie** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Keyboard bug](https://trello.com/c/jgYtIWOI/24-keyboard-bug)

**Comment by kmcknight1** [comment]
Fixed.
