### ISSUE TITLE
Add baseURL inside axiosWithAuth function

### ISSUE THREAD

**Issue by DevWarr** [Lambda-School-Labs/cooking-recipe-source-control-fe#38]
https://github.com/Lambda-School-Labs/cooking-recipe-source-control-fe/blob/e4238de07c150edeb67336e8b71dcd37af207851/utils/axiosWithAuth.js#L5-L10

Adding a baseURL to this function would make it easier to change our baseURL for our production/development/staging/etc environments. 

A potential (untested) solution:
```js
async function axiosWithAuth() {
    const userToken = await AsyncStorage.getItem('userToken');
    // Not 100% sure how this ↓↓↓ part would be typed in react-native
    const baseURL = process.env.URL || "https://recipeshare-development.herokuapp.com/"
    
    return axios.create({headers : {Authorization : userToken}, baseURL})
}
```

**Comment by jambis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add baseURL inside axiosWithAuth function](https://trello.com/c/zK8h7Z8H/56-add-baseurl-inside-axioswithauth-function)

**Comment by jambis** [comment]
I have gone and implemented a baseURL and updated the paths of where axiosWithAuth is used. [Pull Request](https://github.com/Lambda-School-Labs/cooking-recipe-source-control-fe/pull/45)

**Comment by DevWarr** [comment]
This issue has been fixed and merged. Closing
